### ISSUE TITLE
Add mission section

### ISSUE THREAD

**Issue by LauraBeatris** [LauraBeatris/floripamais#16]
## Description 

Add mission section. 

## Tasks

- [x] Add mission section 
- [x] Add mission text
- [x] Add vision text 
- [x] Add values text

## Notes

- Each text should have an emoji
- Each text should be extracted to a ``constants`` file in order to be consistent with the codebase
