### ISSUE TITLE
Setup style guide

### ISSUE THREAD

**Issue by LauraBeatris** [LauraBeatris/floripamais#2]
## Description 

Setup style guide using Tailwind CSS, it's a lightweight library, which can improve the bundle size and we don't need a lot more than it provides. 

## Tasks 

- [x] Install Tailwind 
- [x] Add Tailwind config with the theme according to layout 
- [x] Add PostCSS to transform CSS with JS
- [x] Purge unused styles 
  - https://tailwindcss.com/docs/controlling-file-size#removing-unused-css 
  - https://github.com/tailwindlabs/tailwindcss/discussions/1656
  - https://purgecss.com/#sponsors-%F0%9F%A5%B0
