### ISSUE TITLE
Add actions section

### ISSUE THREAD

**Issue by LauraBeatris** [LauraBeatris/floripamais#25]
## Description 

Add actions section. It should show the next and previous actions on sliders. 

If there's no next actions, show text - `Não há ações no momento, mas nos siga nas redes sociais para  mais informaçöes` 

The previous actions will be fetched from the CMS with the next ones, as well. For now, let's set the previous actions as constants and the next actions can be empty. 

![image](https://user-images.githubusercontent.com/48022589/98306374-7a2f1100-1fa2-11eb-8dc5-1319e3129c7b.png)

## Tasks

- [x] Add base structure for the actions section 
- [x] Add generic slider component (It'll be reused on the members section)
- [x] Add next actions slider
- [x] Add previous actions slider
