### ISSUE TITLE
Improve accessibility

### ISSUE THREAD

**Issue by LauraBeatris** [LauraBeatris/floripamais#28]
## Description

The website is with a poorly accessibility performance and it must be fixed 

![image](https://user-images.githubusercontent.com/48022589/98446905-c774c500-20ff-11eb-9a53-cbdece25b642.png)

## Tasks

- [x] The content must be keyboard navigable (with tab and arrow keys)
- [x] Screen reader compliant (with semantic HTML and/or aria attributes) 
- [x] Have a sufficient color contrast. 
- [x] Text content must be no smaller than 16 pixels for primary content and using relative font units like rem will allow browsers with a custom default font size to scale appropriately.
- [x] Do not remove outline styles because it's really important to people that navigate on the site using only the keyboard

## Notes 

Firefox browser provides a dev tool to inspect the browser accessibility tree that might help. It also detects all the accessibility issues.

**Comment by LauraBeatris** [comment]
Maybe we can remove the outline styles just for people that are navigating with mouse - https://raw.githubusercontent.com/nuclei/unfocus/master/dist/unfocus.js

Not sure if it'll be clean but I would rather create a custom hook for it

**Comment by LauraBeatris** [comment]
After doing some tests, the constrast of the introduction section will be improved by adding a pseudo-element with a darker background color 

![Screen Shot 2020-11-07 at 2 21 28 PM](https://user-images.githubusercontent.com/48022589/98447598-cb571600-2104-11eb-9ab4-7c6d994cdc8e.png)
![image](https://user-images.githubusercontent.com/48022589/98447599-cd20d980-2104-11eb-8d9d-fccc72c8c76e.png)

**Comment by LauraBeatris** [comment]
There's an unnecessary ARIA role added to the button wrapper and it's a div, an unfocusable element

![image](https://user-images.githubusercontent.com/48022589/98447802-787e5e00-2106-11eb-8bdc-577f45c8edef.png)

![Screen Shot 2020-11-07 at 2 35 44 PM](https://user-images.githubusercontent.com/48022589/98447834-b4192800-2106-11eb-8bed-6a592c225e04.png)

**Comment by LauraBeatris** [comment]
The headings of the website should be correctly mapped (h1, h2, etc)

Example:

![image](https://user-images.githubusercontent.com/48022589/98448144-e0ce3f00-2108-11eb-921f-175e4223ab6a.png)

We can use voice-over (Apple accessibility tool) to access it

**Comment by LauraBeatris** [comment]
Might be good to check ARIA authorizing practices https://www.w3.org/TR/wai-aria-practices-1.1/

**Comment by LauraBeatris** [comment]
Check if the accessibility for the navbar button on mobile is correct

![image](https://user-images.githubusercontent.com/48022589/98448683-90f17700-210c-11eb-98e9-f50851e08707.png)

**Comment by LauraBeatris** [comment]
Accessibility tree on chrome may also be a good tool to help fixing the issues 

![image](https://user-images.githubusercontent.com/48022589/98448702-cac27d80-210c-11eb-90de-632752ef01ab.png)

**Comment by LauraBeatris** [comment]
No element offscreen should be focusable. In case of a modal, it should have `tabindex=-1` in order to be programmatically focusable with `focus()`
