### ISSUE TITLE
Implement CMS

### ISSUE THREAD

**Issue by LauraBeatris** [LauraBeatris/floripamais#34]
## Description 

Implement CMS to make the content of the website customizable. 

## Tasks 

- [x] Read docs https://strapi.io/documentation/v3.x/getting-started/introduction.html
- [x] Create strapi app https://strapi.io/documentation/v3.x/installation/cli.html
- [x] Add content
- [x] Add graphql plugin
- [x] Generate types with codegen
- [x] Fetch data on website
- [x] Deploy with Heroku https://strapi.io/documentation/v3.x/deployment/heroku.html
- [x] Trigger website deploy when updating content https://vercel.com/docs/more/deploy-hooks https://strapi.io/blog/webhooks
- [x] Add ``max-width`` to actions name and description on slider

## Notes

Refer to https://blog.logrocket.com/introduction-to-data-fetching-with-next-js-and-strapi-cms/

**Comment by LauraBeatris** [comment]
Would be good to preview the content that wasn't published yet - I created the task on the [Enhancements](https://github.com/LauraBeatris/floripamais/projects/3) project
