### ISSUE TITLE
Improve data fetch

### ISSUE THREAD

**Issue by LauraBeatris** [LauraBeatris/floripamais#38]
## Description 

There are some issues with the way the main page is fetching the data in order to be statically generated 

1. There's no ``try-catch`` block so if the CMS goes down, the website isn't going to build too. 
2. We aren't using the benefits of a query document and instead, recreating a lot of queries even if they are related to the same page. 

## Tasks

- [x] Add one query to fetch all the fields related to the main page 
- [x] Add a try-catch block for the request
- [x] Returns an empty object as props when an error is caught
