### ISSUE TITLE
Improve lint scrips 

### ISSUE THREAD

**Issue by LauraBeatris** [LauraBeatris/floripamais#45]
## Description 

Currently, the ``pre-push`` isn't checking if there are type errors but instead, just lining the codebase according to ``eslint`` rules. 

We should allow commits even if the types are wrong in order to not block and slow the development process. But when pushing changes to the repo, the types must be checked. 

## Tasks 

Add scripts to handle the following cases:

- [x] Check code style according to ``eslint`` rules
- [x] Check types by running the TypeScript compiler 
- [x] To handle all the previous cases 

Example:
```
    "lint-code-style": "eslint ./pages --ext=.ts,.tsx",
    "lint-check-types": "tsc --noemit",
    "linter": "yarn lint-code-style && yarn lint-check-types",
```
